Dailt update :D

diff --git a/.scr/sllogin b/.scr/sllogin
--- a/.scr/sllogin
+++ b/.scr/sllogin
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 
-sudo netctl restart enp0s25-Home && sleep 1
+[[ `netctl status enp0s25-Home | grep -i 'active: active'` ]] || sudo netctl restart enp0s25-Home && sleep 1
 while (true); do
-    curl 'http://222.24.215.2/srun_portal_pc.php' --data 'action=login&ac_id=14&url=&username=2017302344&password=zxcvbnm1234567' --silent > /dev/null
+    res=`curl 'http://222.24.215.2/srun_portal_pc.php' --data 'action=login&ac_id=14&url=&username=2017302344&password=zxcvbnm1234567' --silent`
     [[ $? == 0 ]] || sleep 1 && break
 done
+[[ `echo $res | grep '网络已连接'` ]] || echo -e "\e[1;31mFailed.\e[0m" && echo -e "\e[1;32mSuccess.\e[0m"
+
